---
title: k-Nearest Neighbours
author: Adogbeji Agberien
date: '2021-04-23'
slug: []
categories: []
tags: []
subtitle: ''
summary: 'This post is about k-Nearest Neighbours (k-NN); currently just implementation in R, hopefully will soon update to include the theory of the method'
authors: []
lastmod: '2021-04-23T20:45:35-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

This post is about k-NN; the theory and its implementation in R. Data from [superdatascience](https://www.superdatascience.com/pages/machine-learning). 

```{r warning = F, message = F}
# Install and load packages
required_packages <- c("tidyverse", "data.table", 
                       "caTools", "e1071", "rpart", "randomForest",
                       "class",
                       "rmarkdown", "knitr")

packageCheck <- lapply(required_packages, FUN = function(x) {
  if(!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})
```

```{r echo = F}
# Set the working directory
social_network_ads <- fread("C:/Users/diji_/Desktop/Data Science/Machine Learning A-Z (Codes and Datasets)/Part 3 - Classification/Section 15 - K-Nearest Neighbors (K-NN)/R/Social_Network_Ads.csv")
```

```{r}
head(social_network_ads)
```

```{r}
# Scale the data 
social_network_ads[, c("Age")] <- social_network_ads[, c("Age")] %>% scale()
social_network_ads[, c("EstimatedSalary")] <- social_network_ads[, c("EstimatedSalary")] %>% scale()
```

```{r}
# Split the data into training and test sets 
set.seed(123)
data_split <- sample.split(social_network_ads$Purchased, SplitRatio = 0.8)
training_set <- subset(social_network_ads, data_split == T)
test_set <- subset(social_network_ads, data_split == F)
```

```{r}
# Create the k-NN model 
y_pred <- class::knn(training_set[, c("Age", "EstimatedSalary")], 
                     test_set[, c("Age", "EstimatedSalary")], 
                     cl = training_set$Purchased, 
                     k = 5)
```

```{r}
# Create the confusion matrix 
table(y_pred, test_set$Purchased)
```

```{r}
# Create a grid for visualization
the_grid <- expand.grid(seq(min(test_set$EstimatedSalary), max(test_set$EstimatedSalary), 0.01),
                        seq(min(test_set$Age), max(test_set$Age), 0.01)) %>% data.table() %>% 
  setnames(old = c("Var1", "Var2"), new = c("EstimatedSalary", "Age"))
```

```{r}
y_grid_pred <- class::knn(training_set[, c("Age", "EstimatedSalary")], 
                     the_grid[, c("Age", "EstimatedSalary")], 
                     cl = training_set$Purchased, 
                     k = 5)
```

```{r}
ggplot() +
  geom_point(aes(the_grid$EstimatedSalary, the_grid$Age, colour = as.factor(y_grid_pred), alpha = 0.2)) +
  geom_point(aes(test_set$EstimatedSalary, test_set$Age, colour = as.factor(test_set$Purchased))) +
  xlab("Salary") +
  ylab("Age") +
  ggtitle("k-NN used to determine purchase of an item based on age and salary.") +
  theme_classic()
```
