---
title: Apriori
author: Adogbeji Agberien
date: '2021-04-25'
slug: []
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-04-25T22:08:49-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<p>Say we had a convenient store with some data about the transactions at the store, and most pertinent among our data are the items the customers purchased. For example,</p>
<ul>
<li><p>transaction 1 contained mineral water, milk, energy bar, whole wheat rice, and green tea</p></li>
<li><p>transaction 2 contained burgers, meatballs, and eggs.</p></li>
</ul>
<p>At the store, thousands of transactions have been completed, and our goal is to leverage this data so we can <em>organize our store better</em>. What exactly do I mean by <em>organize our store better?</em> Well, think of it…if we know that the customers who buy eggs also buy milk, we may decide to keep both items closer together, thereby simplifying life for the customer, or, we may keep items further apart so the customer has to walk through the store, take a peek at other items we carry, and perhaps include more in his/her shopping basket.</p>
<p>Apriori can help achieve this goal! The logic behind it is how recommender systems work…you know, <em>users who watched the movie also liked this movie</em> or <em>customers who bought this also bought this</em>. I think you get the point.</p>
<div id="about-the-data" class="section level1">
<h1>About the data</h1>
<p>We have data containing 7501 transactions at the store. The information contained in each transaction is the list of items purchased.</p>
</div>
<div id="analysis" class="section level1">
<h1>Analysis</h1>
<pre class="r"><code># Install and load packages
required_packages &lt;- c(&quot;tidyverse&quot;, &quot;data.table&quot;, 
                       &quot;caTools&quot;, &quot;e1071&quot;, &quot;rpart&quot;, &quot;randomForest&quot;,
                       &quot;arules&quot;,
                       &quot;rmarkdown&quot;, &quot;knitr&quot;)

packageCheck &lt;- lapply(required_packages, FUN = function(x) {
  if(!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})</code></pre>
<pre class="r"><code># Import the data 
market_basket &lt;- fread(&quot;C:/Users/diji_/Desktop/Data Science/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section 28 - Apriori/R/Market_Basket_Optimisation.csv&quot;, header = F, fill = T)</code></pre>
<pre class="r"><code># See the first 5 rows of the data 
market_basket[1:5, 1:5]</code></pre>
<pre><code>##               V1        V2         V3               V4           V5
## 1:        shrimp   almonds    avocado   vegetables mix green grapes
## 2:       burgers meatballs       eggs                              
## 3:       chutney                                                   
## 4:        turkey   avocado                                         
## 5: mineral water      milk energy bar whole wheat rice    green tea</code></pre>
<p>From the above data table we see that the rows are of varying lengths because each transaction contains a different number of items. What we can do to systematically approach our analysis is convert each unique observation into a label i.e. shrimp as column, almond as another column e.t.c. Following that, we can encode each transaction as 1 and 0 depending on whether or not the item was in the specific transaction.</p>
<p>The R package <em>arules</em> simplifies the process of dealing with such sparse data. From <em>arules</em> we use the function <em>read.transactions</em> to import the data and remove duplicates in each transaction. An example of a duplicate is a basket that contains a certain item 2<span class="math inline">\(\times\)</span> or more.</p>
<pre class="r"><code>#Import the data 
market_basket &lt;- read.transactions(&quot;C:/Users/diji_/Desktop/Data Science/Machine Learning A-Z (Codes and Datasets)/Part 5 - Association Rule Learning/Section 28 - Apriori/R/Market_Basket_Optimisation.csv&quot;, sep = &quot;,&quot;, rm.duplicates = T)</code></pre>
<pre><code>## distribution of transactions with duplicates:
## 1 
## 5</code></pre>
<p>The above message following implementation of the function <em>read.transactions</em> implies that there were 5 transactions with duplicates.</p>
<pre class="r"><code>summary(market_basket)</code></pre>
<pre><code>## transactions as itemMatrix in sparse format with
##  7501 rows (elements/itemsets/transactions) and
##  119 columns (items) and a density of 0.03288973 
## 
## most frequent items:
## mineral water          eggs     spaghetti  french fries     chocolate 
##          1788          1348          1306          1282          1229 
##       (Other) 
##         22405 
## 
## element (itemset/transaction) length distribution:
## sizes
##    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
## 1754 1358 1044  816  667  493  391  324  259  139  102   67   40   22   17    4 
##   18   19   20 
##    1    2    1 
## 
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   2.000   3.000   3.914   5.000  20.000 
## 
## includes extended item information - examples:
##              labels
## 1           almonds
## 2 antioxydant juice
## 3         asparagus</code></pre>
<p>When we print a summary of the data as shown above, we see that there are 119 unique items that were purchased as indicated in the number of columns, and 7501 transactions as indicated by the number of rows. The density reflects the proportion of non-zero values, where non-zero implies the purchase of an item. The <em>element (itemset/transaction) length distribution</em> inform on the frequency at which transactions contain certain number of items…i.e., there were 1754 times that a transaction contained only 1 item, there were 1358 times that a transaction contained only 2 items…e.t.c. The quantile distribution informs that the least number of items in a specific transaction was one, the largest number of items was 20, and on average, each transaction contained approximately 4 items.</p>
<p>Let’s take a look at the top 10 items purchased at the store</p>
<pre class="r"><code># Frequency plot of items bought at the store 
itemFrequencyPlot(market_basket, topN = 10)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code># Training the apriori algorithm
association_rules &lt;- apriori(market_basket, parameter = list(supp = 0.005, conf = 0.2))</code></pre>
<pre><code>## Apriori
## 
## Parameter specification:
##  confidence minval smax arem  aval originalSupport maxtime support minlen
##         0.2    0.1    1 none FALSE            TRUE       5   0.005      1
##  maxlen target  ext
##      10  rules TRUE
## 
## Algorithmic control:
##  filter tree heap memopt load sort verbose
##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
## 
## Absolute minimum support count: 37 
## 
## set item appearances ...[0 item(s)] done [0.00s].
## set transactions ...[119 item(s), 7501 transaction(s)] done [0.00s].
## sorting and recoding items ... [101 item(s)] done [0.00s].
## creating transaction tree ... done [0.00s].
## checking subsets of size 1 2 3 4 done [0.00s].
## writing ... [599 rule(s)] done [0.00s].
## creating S4 object  ... done [0.00s].</code></pre>
<pre class="r"><code>inspect(sort(association_rules, by = &quot;lift&quot;)[1:10])</code></pre>
<pre><code>##      lhs                              rhs                 support    
## [1]  {pasta}                       =&gt; {escalope}          0.005865885
## [2]  {pasta}                       =&gt; {shrimp}            0.005065991
## [3]  {whole wheat pasta}           =&gt; {olive oil}         0.007998933
## [4]  {herb &amp; pepper,spaghetti}     =&gt; {ground beef}       0.006399147
## [5]  {herb &amp; pepper,mineral water} =&gt; {ground beef}       0.006665778
## [6]  {tomato sauce}                =&gt; {ground beef}       0.005332622
## [7]  {mushroom cream sauce}        =&gt; {escalope}          0.005732569
## [8]  {frozen vegetables,spaghetti} =&gt; {tomatoes}          0.006665778
## [9]  {mineral water,soup}          =&gt; {olive oil}         0.005199307
## [10] {spaghetti,tomatoes}          =&gt; {frozen vegetables} 0.006665778
##      confidence coverage   lift     count
## [1]  0.3728814  0.01573124 4.700812 44   
## [2]  0.3220339  0.01573124 4.506672 38   
## [3]  0.2714932  0.02946274 4.122410 60   
## [4]  0.3934426  0.01626450 4.004360 48   
## [5]  0.3906250  0.01706439 3.975683 50   
## [6]  0.3773585  0.01413145 3.840659 40   
## [7]  0.3006993  0.01906412 3.790833 43   
## [8]  0.2392344  0.02786295 3.498046 50   
## [9]  0.2254335  0.02306359 3.423030 39   
## [10] 0.3184713  0.02093054 3.341054 50</code></pre>
<p><em>Credit to (SuperDataScience)[] for the data and tutorial.</em></p>
</div>
