---
title: "Fall 2021 Shopify Data Science Challenge"
author: Adogbeji Agberien
date: '2021-05-04'
slug: []
categories: []
tags: []
subtitle: ''
summary: 'Shopify Data Science challenge in which some problems were produced and solutions were provided using both R programming and SQL.'
authors: []
lastmod: '2021-05-04T15:19:57-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<div id="question-1" class="section level1">
<h1>QUESTION 1</h1>
<div id="problem-statement" class="section level2">
<h2>Problem statement</h2>
<p>On Shopify, we have exactly 100 sneaker shops, and each of these shops sells only one model of shoe. We want to do some analysis of the average order value (AOV). When we look at orders data over a 30 day window, we naively calculate an AOV of $3145.13. Given that we know these shops are selling sneakers, a relatively affordable item, something seems wrong with our analysis.</p>
<ul>
<li>Think about what could be going wrong with our calculation. Think about a better way to evaluate this data.</li>
<li>What metric would you report for this dataset?</li>
<li>What is its value?</li>
</ul>
</div>
<div id="analysis-comprehension" class="section level2">
<h2>Analysis comprehension</h2>
<p>What information do we seek?</p>
<p>Well, since the average order value of a 30-day window is being reported, it means that we want information on the average amount spent each time a customer places an order.</p>
<p>AOV <span class="math inline">\(= \frac{R}{N}\)</span> where <span class="math inline">\(R\)</span> = Revenue, and <span class="math inline">\(N\)</span> = no of orders.</p>
<ol style="list-style-type: lower-alpha">
<li>Given that sneakers are affordable items, an AOV of $3,145.13 is intuitively absurd, but only through analysis can we confirm this. Some possible contenders for such an AOV are</li>
</ol>
<ul>
<li>Insufficient analytics (e.g. wrong formulas being utilized)</li>
<li>Presence of outliers in terms of order amount</li>
<li>a small/wrongly calculated <span class="math inline">\(N\)</span> value and large <span class="math inline">\(R\)</span></li>
</ul>
<p>Analytics approach</p>
<p>Our analytics will depend on the depth of information we seek, but say we just need a basic perfomance metric that informs on how much customers spend each time they place an order, then we could</p>
<ul>
<li>Perform exploratory data analysis (EDA) to evaluate the presence of outliers</li>
<li>Depending on the outcome of EDA, we could report the mean or median with confidence interval</li>
</ul>
</div>
<div id="lets-begin-the-analytics" class="section level2">
<h2>Let’s begin the analytics</h2>
<pre class="r"><code># Load the necessary packages 
required_packages &lt;- c(&quot;tidyverse&quot;, &quot;data.table&quot;, &quot;gsheet&quot;,
                       &quot;Hmisc&quot;, &quot;psych&quot;, &quot;lubridate&quot;,
                       &quot;rmarkdown&quot;, &quot;knitr&quot;)

packageCheck &lt;- lapply(required_packages, FUN = function(x) {
  if(!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})</code></pre>
<pre class="r"><code># Import the data 
shopify_sales &lt;- gsheet2tbl(&quot;https://docs.google.com/spreadsheets/d/16i38oonuX1y1g7C_UAmiK9GkY7cS-64DfiDMNiR41LM/edit#gid=0&quot;)</code></pre>
<p>Let us begin by getting summary statistics on the pooled data as it pertains to AOV</p>
<pre class="r"><code># Get basic summary statistics on the data
psych::describe(shopify_sales[, c(&quot;order_amount&quot;, &quot;total_items&quot;)])</code></pre>
<pre><code>##              vars    n    mean       sd median trimmed    mad min    max  range
## order_amount    1 5000 3145.13 41282.54    284  287.39 174.95  90 704000 703910
## total_items     2 5000    8.79   116.32      2    1.88   1.48   1   2000   1999
##               skew kurtosis     se
## order_amount 16.67   279.51 583.82
## total_items  17.06   288.96   1.65</code></pre>
<p>Immediately, we observe things such as the huge standard deviation relative to mean for both the order amount and total items i.e. </p>
<ul>
<li>Order amount: <span class="math inline">\(3145.13 \pm 41282.54\)</span></li>
<li>Total items: <span class="math inline">\(8.79 \pm 116.32\)</span></li>
</ul>
<p>The relatively large deviations from the mean immediately inform us high variance in the data set and possible presence of outliers. The standard error for the order amount is thus high and informs that the mean is likely an inaccurate representation of the true mean.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>What metric would you report for this dataset?</li>
</ol>
<p>In this scenario, it is more appropriate to report the median as opposed to the mean because the median is more robust against outliers. We can thus report a value of $284, albeit the presence of outliers in the data.</p>
<p>Let us do some more exploratory data analysis, following separation of the order amount into a subset excluding the outliers.</p>
<pre class="r"><code># Make box-plot to visualize basis summary content of data 
order_amount_boxplot_full &lt;- boxplot(shopify_sales$order_amount, plot = T)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Immediately we see that outliers are indeed present, and the scale of these outliers relative to our data is so much that we are unable to evaluate the non-outlier subset of data within our data set. On that note, let us do another visualization without the outliers, but not discard the outliers though, as they may be interesting components of our data that we may want to further evaluate.</p>
<pre class="r"><code># Store outliers
order_amount_outliers &lt;- order_amount_boxplot_full$out
describe(order_amount_outliers)</code></pre>
<pre><code>##    vars   n     mean       sd median  trimmed    mad min    max  range skew
## X1    1 141 101407.6 225491.5   1056 39221.84 474.43 735 704000 703265 2.25
##    kurtosis       se
## X1     3.17 18989.81</code></pre>
<pre class="r"><code># Get order amounts not in outliers 
order_amount_no_outliers &lt;- shopify_sales$order_amount[-which(shopify_sales$order_amount %in% order_amount_outliers)]
describe(order_amount_no_outliers)</code></pre>
<pre><code>##    vars    n   mean     sd median trimmed    mad min max range skew kurtosis
## X1    1 4859 293.72 144.45    280  279.23 167.53  90 730   640 0.73    -0.17
##      se
## X1 2.07</code></pre>
<pre class="r"><code># Let us make another plot showing the distribution of the data 
boxplot(order_amount_no_outliers)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Let up apply some more intuition before reporting metrics on our analysis. Firstly, it is mentioned that we seek data over 30 days, so let us confirm that we do indeed have 30 days worth of data in our data set</p>
<pre class="r"><code>shopify_sales$created_at &lt;- ymd_hms(shopify_sales$created_at)
max(shopify_sales$created_at) - min(shopify_sales$created_at)</code></pre>
<pre><code>## Time difference of 29.99127 days</code></pre>
<p>Ok, we are good to go.</p>
<p>Next, what percentage of our data are outliers; a confirmation that we aren’t discarding much of our data.</p>
<pre class="r"><code>cat(&quot;Outlier percentage of data:&quot;, (length(order_amount_outliers)/nrow(shopify_sales)) * 100)</code></pre>
<pre><code>## Outlier percentage of data: 2.82</code></pre>
<pre class="r"><code>cat(&quot;\nWe are reporting based on&quot;, length(order_amount_no_outliers), &quot;no of transactions in 30 days, i.e.&quot;, length(order_amount_no_outliers)/nrow(shopify_sales) * 100, &quot;percent of our data&quot;)</code></pre>
<pre><code>## 
## We are reporting based on 4859 no of transactions in 30 days, i.e. 97.18 percent of our data</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>What is its value?</li>
</ol>
<pre class="r"><code>cat(&quot;In 30 days of sales, the metrics are: &quot;,
    &quot;\n1) The mean value when outliers are included =&quot;,
    describe(shopify_sales$order_amount)$mean,
    &quot;\n2) the mean value when outliers are excluded =&quot;,
    describe(order_amount_no_outliers)$mean, 
    &quot;\n3) the median value when outliers are included =&quot;, 
    describe(shopify_sales$order_amount)$median,
    &quot;\n4) the median value when outliers are excluded =&quot;,
    describe(order_amount_no_outliers)$median)</code></pre>
<pre><code>## In 30 days of sales, the metrics are:  
## 1) The mean value when outliers are included = 3145.128 
## 2) the mean value when outliers are excluded = 293.7154 
## 3) the median value when outliers are included = 284 
## 4) the median value when outliers are excluded = 280</code></pre>
<p>Any of metrics 2 to 4 will be appropriate to return, in this case I will proceed with options 1 or 3, depending on whom the information will be presented to. If it is an in-house presentation, I can inform that the AOV was $3,145.13, but this included 141 transactions that are likely outliers given their order amounts relative to other transaction that occurred. because it considers all the data given. For a general presentation, I can report a value of $284.00 because it contains all transactions, yet, it is not heavily impacted by outliers.</p>
</div>
</div>
<div id="question-2" class="section level1">
<h1>QUESTION 2</h1>
<div id="sql-query-challenge" class="section level2">
<h2>SQL Query Challenge</h2>
<ol style="list-style-type: lower-alpha">
<li>How many orders were shipped by Speedy Express in total?</li>
</ol>
<ul>
<li>In total, there were <strong>54</strong> orders shipped by Speedy Express</li>
</ul>
<p>Code logic:</p>
<ul>
<li><p>We want to know how many orders were shipped by one of the shipping companies, <em>Shippers</em>. This means that firstly, we have to query the database to access the table containing the different shipping companies and their IDs, and select the information pertaining the company whose information we seek, i.e. <em>Speedy Express</em>.</p></li>
<li><p>Next, we go a level up to find the number of orders that were shipped by <em>Speedy Express</em>. This means we have to access the orders table within the database and find the linkage parameter between the <em>Shippers</em> table and the <em>Orders</em> table. Upon finding this linkage parameter, we perform our computation on the <em>Orders</em> table, querying to find the requested information, and next, we link to the <em>Shippers</em> table using the linkage parameters, reporting only the required information.</p></li>
</ul>
<p>Code chunk:</p>
<pre class="sql"><code>SELECT COUNT(*) AS &quot;Speedy_Express_Order_Count&quot; 
FROM Orders
WHERE Orders.ShipperID = 
(
  SELECT ShipperID 
  FROM Shippers 
  WHERE ShipperName = &quot;Speedy Express&quot;
  );</code></pre>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the last name of the employee with the most orders?</li>
</ol>
<ul>
<li>The last name of the employee with the most orders is <strong>Peacock</strong></li>
</ul>
<p>Code logic:</p>
<ul>
<li>Much like the previous question, we have to find linkage parameters contained in the different tables within the database. However, compared to the previous example, other SQL functions such JOIN, GROUP BY, ORDER BY, and LIMIT need to be called at different stages of our query to ensure that at each step, the appropriate information being sought is provided.</li>
</ul>
<p>Code chunk:</p>
<pre class="sql"><code>SELECT Employees.LastName
FROM Employees
LEFT JOIN Orders
ON Orders.EmployeeID = Employees.EmployeeID
GROUP BY Orders.EmployeeID
ORDER BY COUNT(Orders.EmployeeID) DESC
LIMIT 1;</code></pre>
<ol start="3" style="list-style-type: lower-alpha">
<li>What product was ordered the most by customers in Germany?</li>
</ol>
<ul>
<li><strong>Boston Crab Meat</strong> was the product ordered the most by customers in Germany</li>
</ul>
<p>Code logic:</p>
<ul>
<li>Once again, logic takes the helm as we have to find linkage parameters contained in the different tables within the database, albeit with several linkages connecting the different tables.</li>
</ul>
<p>Code chunk:</p>
<pre class="sql"><code>SELECT 
Products.ProductName, SUM(OrderDetails.Quantity) AS Total_orders, Customers.Country
FROM Products
JOIN OrderDetails ON OrderDetails.ProductID = Products.ProductID
JOIN Orders ON Orders.OrderID = OrderDetails.OrderID
JOIN Customers ON Customers.CustomerID = Orders.CustomerID
WHERE Customers.Country = &quot;Germany&quot;
GROUP BY Products.ProductName
ORDER BY Total_orders DESC
LIMIT 1;</code></pre>
</div>
</div>
