---
title: Support Vector Machines with Non-linear kernels
author: Adogbeji Agberien
date: '2021-04-24'
slug: []
categories: []
tags: []
subtitle: ''
summary: 'This post is about non-linear Support Vector Machines; currently just implementation in R, hopefully will soon update to include the theory of the method'
authors: []
lastmod: '2021-04-24T13:14:52-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r warning = F, message = F}
# Install and load packages
required_packages <- c("tidyverse", "data.table", 
                       "caTools", "e1071", "rpart", "randomForest",
                       "class",
                       "rmarkdown", "knitr")

packageCheck <- lapply(required_packages, FUN = function(x) {
  if(!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})
```

```{r echo = F}
# Set the working directory
social_network_ads <- fread("C:/Users/diji_/Desktop/Data Science/Machine Learning A-Z (Codes and Datasets)/Part 3 - Classification/Section 17 - Kernel SVM/R/Social_Network_Ads.csv")
```

```{r}
head(social_network_ads)
```

```{r}
# Scale the data 
social_network_ads[, c("Age")] <- social_network_ads[, c("Age")] %>% scale()
social_network_ads[, c("EstimatedSalary")] <- social_network_ads[, c("EstimatedSalary")] %>% scale()
```

```{r}
# Split the data into training and test sets
set.seed(123)
data_split <- sample.split(social_network_ads$Purchased, SplitRatio = 0.8)
training_set <- subset(social_network_ads, data_split == T)
test_set <- subset(social_network_ads, data_split == F)
```

```{r}
# Create the linear svm model
svm_rb <- svm(Purchased ~ Age + EstimatedSalary, data = training_set, type = "C-classification", kernel = "radial")
summary(svm_rb)
```

```{r}
# Make predictions on the test set
test_predictions <- predict(svm_rb, test_set)
```

```{r}
# Create the confusion matrix
table(test_predictions, test_set$Purchased)
```

```{r}
# Create a grid for visualization
the_grid <- expand.grid(seq(min(test_set$EstimatedSalary), max(test_set$EstimatedSalary), 0.01),
                        seq(min(test_set$Age), max(test_set$Age), 0.01)) %>% data.table() %>% 
  setnames(old = c("Var1", "Var2"), new = c("EstimatedSalary", "Age"))
```

```{r}
y_grid_pred <- predict(svm_rb, the_grid)
```

```{r}
ggplot() +
  geom_point(aes(the_grid$EstimatedSalary, the_grid$Age, colour = as.factor(y_grid_pred), alpha = 0.2)) +
  geom_point(aes(test_set$EstimatedSalary, test_set$Age, colour = as.factor(test_set$Purchased)), colour = if_else(test_set$Purchased == 1, "black", "yellow")) +
  xlab("Salary") +
  ylab("Age") +
  ggtitle("SVM with radial basis kernel used to determine purchase of an item based on age and salary.") +
  theme_classic() +
  theme(legend.position = "none")
```
