---
title: Support Vector Regression
author: Adogbeji Agberien
date: '2021-04-23'
slug: []
categories: []
tags: []
subtitle: ''
summary: 'This post is about Support Vector Regression; currently just implementation in R, hopefully will soon update to include the theory of the method'
authors: []
lastmod: '2021-04-23T14:05:27-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

This post is about Support Vector Regression, currently just its implementation in R. Hopefully in the coming days I will include the theory of the method. The data was acquired from 
[superdatascience](https://www.superdatascience.com/pages/machine-learning). They do a great job of teaching the topic as well.  

```{r warning=F, message = F}
# Install and load packages
required_packages <- c("tidyverse", "data.table", 
                       "caTools", "e1071",
                       "rmarkdown", "knitr")

packageCheck <- lapply(required_packages, FUN = function(x) {
  if(!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})
```

```{r echo = F}
# Import the data
salary_data <- fread("C:/Users/diji_/Desktop/Data Science/Machine Learning A-Z (Codes and Datasets)/Part 2 - Regression/Section 7 - Support Vector Regression (SVR)/R/Position_Salaries.csv")
```

```{r}
head(salary_data)
```

```{r}
# Fit a SVM model to the data
svm_salary <- svm(Salary ~ Level, data = salary_data, scale = T, type = "eps-regression")
```

```{r}
x_grid = data.frame(Level = seq(min(salary_data$Level), max(salary_data$Level), 0.5))
pred_x_grid = predict(svm_salary, x_grid)
```

```{r}
ggplot() +
  geom_point(aes(salary_data$Level, salary_data$Salary), colour = "black") +
  geom_line(aes(x_grid$Level, pred_x_grid), colour = "red") +
  xlab("Position") +
  ylab("Salary") +
  theme_classic()

```

